### ISSUE TITLE
Expose a USB C female, downstream connector on the case

### ISSUE THREAD

**Issue by bibz** [bibz/atreus#1]
The idea is that we simply use USB 2.0 with the very nice USB C connector.
There is no love left for micro-B USB connectors.

By exposing the female connector on the case, we do not have to glue in a cable.
It sounds like a much better idea to have a removable cable to carry the keyboard around.

Reference builds by:
- mini-B breakout board: [Brendan Mattia](http://www.brendanmattia.com/2016/03/hand-wiring-atreus-step-into-open.html)
- micro-B breakout board: [Simone Gotti](https://sgotti.dev/post/atreus-keyboard-build-log/#adding-an-external-usb-port)
- USB C breakout board: [Henri Bergius](https://bergie.iki.fi/blog/atreus-build-log/#usb-c)

**Comment by bibz** [comment]
Basically, there are two options here:

1. Pick a board that features a USB-C connector;
    - [Elite-C](https://keeb.io/products/elite-c-usb-c-pro-micro-replacement-arduino-compatible-atmega32u4) or [Elite-C LP (Low Profile)](https://keeb.io/products/elite-c-low-profile-version-usb-c-pro-micro-replacement-atmega32u4);
    - [QMK Proton C](https://qmk.fm/proton-c/);
    - [SparkFun Qwiic Pro Micro - USB-C](https://www.sparkfun.com/products/15795);
2. Pick a board with a micro-USB connector (many more available) and connect that to a USB-C breakout board.
    - Any ATmega32U4 / 16MHz board with 15 GPIO available **[1]**;
        - [Adafruit ItsyBitsy 32u4](https://www.adafruit.com/product/3677);
        - Arduino Pro Micro, and clones;
        - [Pololu A-Star 32U4 Micro](https://www.pololu.com/product/3101), the official Atreus recommendation as of yet;
        - [Teensy 2.0](https://www.pjrc.com/store/teensy.html), the board used in the original Atreus;

    - A USB C breakout board (pre-configured for downstream usage);
        - [Adafruit USB C Breakout Board - Downstream Connection](https://www.adafruit.com/product/4090);
        - [Pololu USB 2.0 Type-C Connector Breakout Board](https://www.pololu.com/product/2585);
        - Alternatively, [SparkFun USB-C Breakout](https://www.sparkfun.com/products/15100) but you would have to add a couple of resistors on `CC1` and `CC2` to force the downstream mode, or something like that, not an expert.

Either way, I'd like to adapt the case spacer layer to be able to fasten the USB C board with e.g. screws. Most of the builds simply glue up the board but I am wary of how it hold though time.

**[1]**: This is not a hard requirement, simply matching the original Atreus design. I am not even sure if we need the 16MHz or if 8MHz would be enough.

**Comment by bibz** [comment]
Regarding boards with a USB-C connector: Other options I found are either not mass produced, or substantially more expensive (+50%).

The three board mentioned earlier are unfortunately not open source.
On the other hand, the Arduino Pro Micro is. The breakout boards might not be, but they are much simpler (connector, resistors, and simple routing). I can live with that.

Regarding the fastening of the board, none of the boards I listed offer fastening holes. The breakout boards do, though.
That is clearly a bonus point for the composite approach: which board we use does not matter so much, it will be glued and connected to a breakout board. The breakout board would then be fastened with the same screws that hold the case layers together, making it a really stable assembly. I think this makes sense.

**Comment by swrichards** [comment]
I am happy with using the Arduino for this (and a non-OS board feels a bit contrary to the spirit of the project, no?), or any of the other microcontrollers, though not quite sure how to pick between them. Why would we not go for the official recommendation?

Still not entirely clear to me how the Arduino would be affixed to the case (but this is mainly due to lack of research, which I am slowly remedying), but it seems to me at first glance  that having the usb breakout would give us a bit more flexibility in terms of case layout, no?

**Comment by swrichards** [comment]
(Re the boards: are there any firmware limitations to be aware of?)

**Comment by bibz** [comment]
> I am happy with using the Arduino for this (and a non-OS board feels a bit contrary to the spirit of the project, no?), or any of the other microcontrollers, though not quite sure how to pick between them. Why would we not go for the official recommendation?

Yes, I agree, it seems better and more consistent to go with an OS hardware.
No reason to not choose the (recommended) Pololu A-star besides of limited availability in Europe.

> Still not entirely clear to me how the Arduino would be affixed to the case (but this is mainly due to lack of research, which I am slowly remedying), but it seems to me at first glance that having the usb breakout would give us a bit more flexibility in terms of case layout, no?

In the original design the board is held thanks to the wires soldered to it. Many logs refer to using hot glue to secure it where it stands. Also, the USB cable would be pinched between the spacers, giving even less space for the board to move.

The breakout board adds flexibility in terms of which main board you can use, but not so much in terms of placement because then it becomes a really tight fit in the case. This is still my preferred option.

**Comment by bibz** [comment]
> (Re the boards: are there any firmware limitations to be aware of?)

No they should all be compatible with e.g. [QMK](https://qmk.fm), or home-made firmware ;-).
